services:
  backend:
    image: media-backend
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - 3001:3001
    environment:
      - MONGODB_URL=mongodb://root:example@mongo:27017
  database:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example