PUT http://localhost:3001/api/movies/log/6a328b70e6f4cc73bc991bd6
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RuYW1lIiwiaWQiOiI2YTMyOGE0YWM2ZjA4ZGYzM


{
    "rating": 10
}