POST http://localhost:3001/api/movies/log
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RuYW1lIiwiaWQiOiI2YTMyOGE0YWM2ZjA4ZGYzMjVhODhlNTUiLCJpYXQiOjE3ODE2OTcxNjh9.VBy8VGKHltVrj7CHlzFiRttRAmN3vgt0A7eJM5Wdvj0


{
    "movieId": 106,
    "watched": true
}